name: 'Upload artifacts'
description: 'Uploads build artifacts to S3'
runs:
  using: docker
  image: Dockerfile
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKey }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretKey }}
  S3_BUCKET: "presto-ci-test"
  S3_BUCKET_REGION: "us-east-2"
  S3_BUCKET_ENDPOINT: "s3.us-east-2.amazonaws.com"
  SHA: ${{ github.sha }}
